[package]
name = "ya-runtime-api"
version = "0.3.0"
authors = ["Golem Factory <contact@golem.network>"]
edition = "2018"

[[example]]
name = "runtime-server-mock"
required-features = ["server"]

[features]
default = ['server']
codec = []
server = [
    'prost' ,
    'futures',
    'tokio',
    'tokio-util'
]

[dependencies]
anyhow = "1.0.31"
bytes = "1.0"
futures = { version = "0.3", optional = true  }
log = "0.4.8"
prost = { version = "0.7", optional = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.6" , optional = true, features = ["io-std", "rt", "process", "sync"] }
tokio-util = { version = "0.6.7", optional = true, features = ["codec"] }

[build-dependencies]
prost-build = "0.6.1"

[dev-dependencies]
tokio = { version = "1.6" , features = ["macros", "time"] }
env_logger = "0.7"
