[package]
name = "ya-service-api-interfaces"
version = "0.1.0"
authors = ["Golem Factory <contact@golem.network>"]
edition = "2018"

[dependencies]
actix-web = "=4.0.0-beta.5"
anyhow = "1.0"
futures = "0.3"
